### ISSUE TITLE
Dynamic data not working.

### ISSUE THREAD

**Issue by simphonydeveloper** [dingyi222666/TreeView#14]
```kotlin

class FileActivity : AppCompatActivity() {

    private lateinit var binding: ActivityFileBinding

    //private lateinit var tree: Tree<TreeNode2>
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityFileBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val trees = createTree()

        (binding.treeview as TreeView<TreeNode2>).apply {
            bindCoroutineScope(lifecycleScope)
            this.tree = trees
            binder = ViewBinder()
            nodeEventListener = binder as TreeNodeEventListener<TreeNode2>
        }

        lifecycleScope.launch {
            binding.treeview.refresh()
        }
    }

    private fun createTree(): Tree<TreeNode2> {

        val rootNode1 = TreeNode2("1", "Root 1")
        val child1 =
            TreeNode2("1.1", "Child 1", parent = rootNode1)
        val child2 =
            TreeNode2("1.2", "Child 2", parent = rootNode1)
        val grandChild1 =
            TreeNode2("1.2.1", "Grandchild 1", parent = child2)
        child2.children.add(grandChild1)
        rootNode1.children.addAll(listOf(child1, child2))
        return Tree.createTree<TreeNode2>().apply {
            generator = ItemTreeNodeGenerator(rootNode1)
            initTree()
        }
    }

}


 class ViewBinder : TreeViewBinder<TreeNode2>(),
    TreeNodeEventListener<TreeNode2> {

    override fun createView(parent: ViewGroup, viewType: Int): View {
        val layoutInflater = LayoutInflater.from(parent.context)
        return if (viewType == 1) {
            ItemDirBinding.inflate(layoutInflater, parent, false).root
        } else {
            ItemFileBinding.inflate(layoutInflater, parent, false).root
        }
    }

    override fun getItemViewType(node: TreeNode<TreeNode2>): Int {
        if (node.data!!.children.isNotEmpty()) {
            return 1
        }
        return 0
    }

    override fun bindView(
        holder: TreeView.ViewHolder,
        node: TreeNode<TreeNode2>,
        listener: TreeNodeEventListener<TreeNode2>
    ) {
        if (node.data!!.children.isNotEmpty()) {
            applyDir(holder, node)
        } else {
            applyFile(holder, node)
        }

        val itemView = holder.itemView.findViewById<Space>(R.id.space)

        itemView.updateLayoutParams<ViewGroup.MarginLayoutParams> {
            width = node.depth * 22
        }

    }

    private fun applyFile(holder: TreeView.ViewHolder, node: TreeNode<TreeNode2>) {
        val binding = ItemFileBinding.bind(holder.itemView)
        binding.tvName.text = node.data!!.name.toString()
    }

    private fun applyDir(holder: TreeView.ViewHolder, node: TreeNode<TreeNode2>) {
        val binding = ItemDirBinding.bind(holder.itemView)
        binding.tvName.text = node.data!!.name.toString()

        binding
            .ivArrow
            .animate()
            .rotation(if (node.data!!.isExpanded) 90f else 0f)
            .setDuration(200)
            .start()
    }


    override fun onClick(node: TreeNode<TreeNode2>, holder: TreeView.ViewHolder) {
        if (node.data!!.children.isNotEmpty()) {
            applyDir(holder, node)
        } else {
            //Toast.makeText(this@MainActivity, "Clicked ${node.name}", Toast.LENGTH_LONG).show()
        }
    }

    override fun onToggle(
        node: TreeNode<TreeNode2>,
        isExpand: Boolean,
        holder: TreeView.ViewHolder
    ) {
        applyDir(holder, node)
    }
}

 class ItemTreeNodeGenerator(
    private val rootItem: TreeNode2
) : TreeNodeGenerator<TreeNode2> {
     suspend fun fetchNodeChildData(targetNode: TreeNode<TreeNode2>): Set<TreeNode2> {
         return targetNode.requireData().children.toSet()
     }

    override fun createNode(
        parentNode: TreeNode<TreeNode2>,
        currentData: TreeNode2,
        tree: AbstractTree<TreeNode2>
    ): TreeNode<TreeNode2> {
        return TreeNode(
            data = currentData,
            depth = parentNode.depth + 1,
            name = currentData.name,
            id = tree.generateId(),
            hasChild = currentData.children.isNotEmpty(),
            // It should be taken from the Item
            isChild = currentData.children.isNotEmpty(),
            expand = false
        )
    }

    override fun createRootNode(): TreeNode<TreeNode2> {
        return TreeNode(
            data = rootItem,
            // Set to -1 to not show the root node
            depth = -1,
            name = rootItem.name,
            id = Tree.ROOT_NODE_ID,
            hasChild = true,
            isChild = true
        )
    }

     override suspend fun fetchChildData(targetNode: TreeNode<TreeNode2>): Set<TreeNode2> {
         return targetNode.requireData().children.toSet()
     }


 }
```
```kotlin

data class TreeNode2(
    val id: String,
    val name: String,
    val children: MutableList<TreeNode2> = mutableListOf(),
    var isExpanded: Boolean = false,
    var level: Int = 0,
    var isSwitchOn: Boolean = false,
    var parent: TreeNode2? = null 
)
```
Part of my inspiration comes from here.
https://github.com/dingyi222666/TreeView/issues/4
It seems to have entered an infinite loop problem.

this is my version 
io.github.dingyi222666:treeview:1.3.1

Thanks
ERROR:
```txt
AndroidRuntime          com.example.myapplicationtest        E  	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.ArrayList.hashCodeRange(ArrayList.java:684)
                                                                                                    	at java.util.ArrayList.hashCode(ArrayList.java:671)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:19)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.ArrayList.hashCodeRange(ArrayList.java:684)
                                                                                                    	at java.util.ArrayList.hashCode(ArrayList.java:671)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:19)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.ArrayList.hashCodeRange(ArrayList.java:684)
                                                                                                    	at java.util.ArrayList.hashCode(ArrayList.java:671)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:19)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.ArrayList.hashCodeRange(ArrayList.java:684)
                                                                                                    	at java.util.ArrayList.hashCode(ArrayList.java:671)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:19)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.ArrayList.hashCodeRange(ArrayList.java:684)
                                                                                                    	at java.util.ArrayList.hashCode(ArrayList.java:671)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:19)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.ArrayList.hashCodeRange(ArrayList.java:684)
                                                                                                    	at java.util.ArrayList.hashCode(ArrayList.java:671)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:19)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.ArrayList.hashCodeRange(ArrayList.java:684)
                                                                                                    	at java.util.ArrayList.hashCode(ArrayList.java:671)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:19)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.ArrayList.hashCodeRange(ArrayList.java:684)
                                                                                                    	at java.util.ArrayList.hashCode(ArrayList.java:671)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:19)
                                                                                                    	at com.example.myapplicationtest.model.TreeNode2.hashCode(Unknown Source:61)
                                                                                                    	at java.util.HashMap.hash(HashMap.java:337)
                                                                                                    	at java.util.HashMap.put(HashMap.java:617)
                                                                                                    	at java.util.HashSet.add(HashSet.java:229)
                                                                                                    	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1296)
                                                                                                    	at kotlin.collections.CollectionsKt___CollectionsKt.toSet(_Collections.kt:1348)
                                                                                                    	at com.example.myapplicationtest.ItemTreeNodeGenerator.fetchChildData(FileActivity.kt:197)
                                                                                                    	at io.github.dingyi222666.view.treeview.Tree.refreshInternal(trees.kt:206)
                                                                                                    	at io.github.dingyi222666.view.treeview.Tree.refresh(trees.kt:231)
                                                                                                    	at io.github.dingyi222666.view.treeview.Tree.getChildNodesInternal(trees.kt:103)
                                                                                                    	at io.github.dingyi222666.view.treeview.Tree.visitInternal(trees.kt:338)
                                                                                                    	at io.github.dingyi222666.view.treeview.Tree.visit(trees.kt:297)
                                                                                                    	at io.github.dingyi222666.view.treeview.AbstractTreeKt.toSortedList(AbstractTree.kt:408)
                                                                                                    	at io.github.dingyi222666.view.treeview.AbstractTreeKt.toSortedList$default(AbstractTree.kt:383)
                                                                                                    	at io.github.dingyi222666.view.treeview.TreeView.refresh(TreeView.kt:173)
                                                                                                    	at io.github.dingyi222666.view.treeview.TreeView.refresh$default(TreeView.kt:157)
                                                                                                    	at com.example.myapplicationtest.FileActivity$onCreate$2.invokeSuspend(FileActivity.kt:63)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
2024-11-27 13:28:55.527 10530-10530 AndroidRuntime          com.example.myapplicationtest        E  	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.example.myapplicationtest.FileActivity.onCreate(FileActivity.kt:62)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9002)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by dingyi222666** [comment]
Your `TreeNode2` class should not contain the `parent` field. Remove it and try again.

**Comment by simphonydeveloper** [comment]
thank you,
it's working.
i want to know,Can this component work well with Switch?
Thanks again.

**Comment by dingyi222666** [comment]
It's okay. Check out the code https://github.com/dingyi222666/TreeView/blob/1706aca5112f2760c20a0f3f5ad2f3b73a4def42/treeview/src/main/kotlin/io/github/dingyi222666/view/treeview/TreeView.kt#L912 that supports components that implement the Checkable interface.

**Comment by simphonydeveloper** [comment]
![微信截图_20241127154717](https://github.com/user-attachments/assets/7a1be0fc-c244-4d25-80e3-ab32464f7877)
I haven't implemented getCheckableView. I want to update all child nodes below when changing a parent node, but I couldn't find a parent class in ViewBinding that can operate on all data properties or methods. Perhaps what I did was wrong.

Thanks

**Comment by dingyi222666** [comment]
First implement `getCheckableView`. 

https://github.com/dingyi222666/TreeView/blob/1706aca5112f2760c20a0f3f5ad2f3b73a4def42/app/src/main/kotlin/com/dingyi/treeview/MainActivity.kt#L342-L350

Set the selection mode to `MULTIPLE_WITH_CHILDREN`, then operate on the treeView by calling selectNode to select the corresponding parent node. When this happens, the child nodes will also be updated.

https://github.com/dingyi222666/TreeView/blob/1706aca5112f2760c20a0f3f5ad2f3b73a4def42/app/src/main/kotlin/com/dingyi/treeview/MainActivity.kt#L152-L156

**Comment by simphonydeveloper** [comment]
Sorry,I have reviewed your example, and you executed it through the menu item. How do I perform this operation on the switch of a certain node?

Thanks

```kotlin

 class ViewBinder : TreeViewBinder<TreeNode2>(),
    TreeNodeEventListener<TreeNode2> {

    override fun createView(parent: ViewGroup, viewType: Int): View {
        val layoutInflater = LayoutInflater.from(parent.context)
        return if (viewType == 1) {
            ItemDirBinding.inflate(layoutInflater, parent, false).root
        } else {
            ItemFileBinding.inflate(layoutInflater, parent, false).root
        }
    }

    override fun getItemViewType(node: TreeNode<TreeNode2>): Int {
        if (node.data!!.children.isNotEmpty()) {
            return 1
        }
        return 0
    }

    override fun bindView(
        holder: TreeView.ViewHolder,
        node: TreeNode<TreeNode2>,
        listener: TreeNodeEventListener<TreeNode2>
    ) {
        if (node.data!!.children.isNotEmpty()) {
            applyDir(holder, node)
        } else {
            applyFile(holder, node)
        }

        val itemView = holder.itemView.findViewById<Space>(R.id.space)

//        (getCheckableView(node, holder) as Switch).apply {
//            isVisible = node.selected
//            isSelected = node.selected
//        }

        itemView.updateLayoutParams<ViewGroup.MarginLayoutParams> {
            width = node.depth * 22
        }

    }

     override fun getCheckableView(
         node: TreeNode<TreeNode2>,
         holder: TreeView.ViewHolder
     ): Checkable? {

         return if (node.isChild) {
             ItemDirBinding.bind(holder.itemView).switchOn
         } else {
             ItemFileBinding.bind(holder.itemView).switchOn
         }
         //return  super.getCheckableView(node, holder)
     }

    private fun applyFile(holder: TreeView.ViewHolder, node: TreeNode<TreeNode2>) {
        val binding = ItemFileBinding.bind(holder.itemView)
        binding.tvName.text = node.data!!.name.toString()
    }

     private fun applyDir(holder: TreeView.ViewHolder, node: TreeNode<TreeNode2>) {
         val binding = ItemDirBinding.bind(holder.itemView)
         binding.tvName.text = node.data!!.name.toString()
         binding.switchOn.isChecked =  node.data!!.isSwitchOn
         binding.switchOn.setOnCheckedChangeListener(object :
             CompoundButton.OnCheckedChangeListener {
             override fun onCheckedChanged(p0: CompoundButton?, p1: Boolean) {
//                 node.data!!.isSwitchOn = p1
//                 if (node.hasChild) {
//                     flattenTree(node.data!!.children, p1)
//                 }
/// bad code  
                 lifecycleScope.launch {
                     binding.treeview.apply {
                         // select node and it's children
                         selectionMode = TreeView.SelectionMode.MULTIPLE_WITH_CHILDREN
                         selectNode(binding.treeview.tree.rootNode, true)
                         expandAll()
                         selectionMode = TreeView.SelectionMode.MULTIPLE_WITH_CHILDREN
                     }
                 }
             }
         })

         binding
             .ivArrow
             .animate()
             .rotation(if (node.expand) 180f else 0f)
             .setDuration(200)
             .start()
     }

     fun flattenTree(treeNodes: List<TreeNode2>, isSwitchOn: Boolean): List<TreeNode2> {
         val result = mutableListOf<TreeNode2>()
         for (node in treeNodes) {
             node.isSwitchOn = isSwitchOn
             result.add(node)
             if (node.children.isNotEmpty()) {
                 val flattenedChildren = flattenTree(node.children, isSwitchOn)
                 result.addAll(flattenedChildren)
             }
         }
         return result
     }

//     fun flattenTree(): List<TreeNode2> {
//         val result = mutableListOf<TreeNode2>()
//         for (node in treeNodes) {
//             node.isSwitchOn = isSwitchOn
//             result.add(node)
//             if (node.children.isNotEmpty()) {
//                 val flattenedChildren = flattenTree(node.children, isSwitchOn)
//                 result.addAll(flattenedChildren)
//             }
//         }
//         return result
//     }


    override fun onClick(node: TreeNode<TreeNode2>, holder: TreeView.ViewHolder) {
        if (node.data!!.children.isNotEmpty()) {
            applyDir(holder, node)
        } else {
            //Toast.makeText(this@MainActivity, "Clicked ${node.name}", Toast.LENGTH_LONG).show()
        }
    }

    override fun onToggle(
        node: TreeNode<TreeNode2>,
        isExpand: Boolean,
        holder: TreeView.ViewHolder
    ) {
        applyDir(holder, node)
    }
}

 class ItemTreeNodeGenerator(
    private val rootItem: TreeNode2
) : TreeNodeGenerator<TreeNode2> {
     suspend fun fetchNodeChildData(targetNode: TreeNode<TreeNode2>): Set<TreeNode2> {
         return targetNode.requireData().children.toSet()
     }

    override fun createNode(
        parentNode: TreeNode<TreeNode2>,
        currentData: TreeNode2,
        tree: AbstractTree<TreeNode2>
    ): TreeNode<TreeNode2> {
        return TreeNode(
            data = currentData,
            depth = parentNode.depth + 1,
            name = currentData.name,
            id = tree.generateId(),
            hasChild = currentData.children.isNotEmpty(),
            // It should be taken from the Item
            isChild = currentData.children.isNotEmpty(),
            expand = false
        )
    }

    override fun createRootNode(): TreeNode<TreeNode2> {
        return TreeNode(
            data = rootItem,
            // Set to -1 to not show the root node
            depth = -1,
            name = rootItem.name,
            id = Tree.ROOT_NODE_ID,
            hasChild = true,
            isChild = true
        )
    }

     override suspend fun fetchChildData(targetNode: TreeNode<TreeNode2>): Set<TreeNode2> {
         return targetNode.requireData().children.toSet()
     }


 }
```

**Comment by dingyi222666** [comment]
Upload all your example code to github as a repository, I'll read and modify it later.

**Comment by simphonydeveloper** [comment]
repository:
https://github.com/simphonydeveloper/AndroidTreeViewSample.git

Thanks

**Comment by dingyi222666** [comment]
Okay. You can check out my code example:
https://github.com/dingyi222666/AndroidTreeViewSample

**Comment by simphonydeveloper** [comment]
Thank you!
Great code, I have implemented the simultaneous selection and closure of Switch according to your code.
When all child nodes are selected, the parent node is also selected. This operation needs to be completed in the class `DataSource`, right?
⭐

**Comment by dingyi222666** [comment]
You need to change on both the `DataSource` and the `Tree`.

**Comment by simphonydeveloper** [comment]
Thank you .
 i'm Implemented my need.
bu i think exist a bug. when i manual update parent node selected status it's not updated.
actually. i was updated it.
![image](https://github.com/user-attachments/assets/d970db74-9b2c-4686-af70-8b975f5aa052)

this is my code.

```Kotlin
package com.example.treeviewsample

import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Space
import android.widget.Switch
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.isVisible
import androidx.core.view.updateLayoutParams
import androidx.lifecycle.lifecycleScope
import com.example.treeviewsample.databinding.ActivityMainBinding
import com.example.treeviewsample.databinding.ItemDirBinding
import com.example.treeviewsample.databinding.ItemFileBinding
import io.github.dingyi222666.view.treeview.AbstractTree
import io.github.dingyi222666.view.treeview.Tree
import io.github.dingyi222666.view.treeview.TreeNode
import io.github.dingyi222666.view.treeview.TreeNodeEventListener
import io.github.dingyi222666.view.treeview.TreeNodeGenerator
import io.github.dingyi222666.view.treeview.TreeView
import io.github.dingyi222666.view.treeview.TreeViewBinder
import kotlinx.coroutines.launch

class MainActivity : AppCompatActivity() {
    private lateinit var binding: ActivityMainBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val source = DataSource()
        val trees = createTree(source)
        val binder = ViewBinder()

        (binding.treeview as TreeView<TreeNode2>).apply {
            bindCoroutineScope(lifecycleScope)
            tree = trees
            this.binder = binder
            selectionMode = TreeView.SelectionMode.MULTIPLE_WITH_CHILDREN
            nodeEventListener = binder

            binder.onSelected { node, selected ->
                // selected from data (update data)
                source.select(node.data!!, selected)

                Log.d("MainActivity", "select ${node.data!!.name} $selected")

                // refresh the tree
                lifecycleScope.launch {
//                    selectionMode = if (selected) {
//                        TreeView.SelectionMode.MULTIPLE_WITH_CHILDREN
//                    } else {
//                        TreeView.SelectionMode.MULTIPLE
//                    }
                    selectionMode = TreeView.SelectionMode.MULTIPLE_WITH_CHILDREN
                    binding.treeview.selectNode(node, selected)

                    val parentNode = tree.getParentNode(node)
                    val selectedNode = tree.getSelectedNodes()


                    //no selected
                    if (parentNode != null && parentNode.data!!.children.count { !it.selected } == parentNode.data!!.children.count() && !selected) {
                        binding.treeview.selectNode(parentNode, false)
                        recurseParent(tree, parentNode, false)
                    } else if (parentNode != null && selected && parentNode.data!!.children.count { it.selected } == parentNode.data!!.children.count()) {
                        binding.treeview.selectNode(parentNode, true).apply {
                            recurseParent(tree, parentNode, true)
                        }
                    }

                    Toast.makeText(
                        this@MainActivity,
                        "Selected ${selectedNode.joinToString { it.name.toString() }}.",
                        Toast.LENGTH_LONG
                    ).apply {
                        show()
                    }
                }
            }
        }

        lifecycleScope.launch {
            binding.treeview.refresh()
        }
    }

    /**
     * recurse parent change switch status
     */
    private suspend fun recurseParent(
        tree: Tree<TreeNode2>,
        node: TreeNode<TreeNode2>,
        selected: Boolean
    ) {
        val parentNode = tree.getParentNode(node)

        if (parentNode == null)
            return
        if (parentNode.data!!.children.count { !it.selected } == parentNode.data!!.children.count() && !selected) {
            binding.treeview.selectNode(parentNode, selected)
            recurseParent(tree, parentNode, selected)
        }
        else if(parentNode.data!!.children.count { it.selected } == parentNode.data!!.children.count()) {
            binding.treeview.selectNode(parentNode, selected)
            recurseParent(tree, parentNode, selected)
        }
    }

    private fun createTree(source: DataSource): Tree<TreeNode2> {
        return Tree.createTree<TreeNode2>().apply {
            generator = ItemTreeNodeGenerator(source)
            initTree()
        }
    }


    inner class ViewBinder : TreeViewBinder<TreeNode2>(),
        TreeNodeEventListener<TreeNode2> {

        private var selectedEventListener: (node: TreeNode<TreeNode2>, selected: Boolean) -> Unit =
            { _, _ -> }

        override fun createView(parent: ViewGroup, viewType: Int): View {
            val layoutInflater = LayoutInflater.from(parent.context)
            return if (viewType == 1) {
                ItemDirBinding.inflate(layoutInflater, parent, false).root
            } else {
                ItemFileBinding.inflate(layoutInflater, parent, false).root
            }
        }

        override fun getItemViewType(node: TreeNode<TreeNode2>): Int {
            if (node.data!!.children.isNotEmpty()) {
                return 1
            }
            return 0
        }

        override fun bindView(
            holder: TreeView.ViewHolder,
            node: TreeNode<TreeNode2>,
            listener: TreeNodeEventListener<TreeNode2>
        ) {
            if (node.data!!.children.isNotEmpty()) {
                applyDir(holder, node)
            } else {
                applyFile(holder, node)
            }

            val itemView = holder.itemView.findViewById<Space>(R.id.space)


            (getCheckableView(node, holder)).apply {
                setOnCheckedChangeListener { _, selected ->
                    selectedEventListener.invoke(node, selected)
                }
            }

            itemView.updateLayoutParams<ViewGroup.MarginLayoutParams> {
                width = node.depth * 22
            }

        }

        override fun getCheckableView(
            node: TreeNode<TreeNode2>,
            holder: TreeView.ViewHolder
        ): Switch {

            return if (node.isChild) {
                ItemDirBinding.bind(holder.itemView).switchOn
            } else {
                ItemFileBinding.bind(holder.itemView).switchOn
            }
            //return  super.getCheckableView(node, holder)
        }

        private fun applyFile(holder: TreeView.ViewHolder, node: TreeNode<TreeNode2>) {
            val binding = ItemFileBinding.bind(holder.itemView)
            binding.tvName.text = node.data!!.name
        }

        private fun applyDir(holder: TreeView.ViewHolder, node: TreeNode<TreeNode2>) {
            val binding = ItemDirBinding.bind(holder.itemView)
            binding.tvName.text = node.data!!.name


            binding
                .ivArrow
                .animate()
                .rotation(if (node.expand) 180f else 0f)
                .setDuration(200)
                .start()
        }


        override fun onClick(node: TreeNode<TreeNode2>, holder: TreeView.ViewHolder) {
            Toast.makeText(this@MainActivity, "Clicked ${node.name}", Toast.LENGTH_LONG).show()
        }


        // call when the node has children
        override fun onToggle(
            node: TreeNode<TreeNode2>,
            isExpand: Boolean,
            holder: TreeView.ViewHolder
        ) {
            applyDir(holder, node)
        }

        fun onSelected(listener: (node: TreeNode<TreeNode2>, selected: Boolean) -> Unit) {
            selectedEventListener = listener
        }
    }
}


class DataSource {
    val root = TreeNode2("1", "Root 1")

    init {
        initData(root)
    }

    private fun initData(root: TreeNode2) {
        val child1 = TreeNode2("1.1", "Child 1")
        val child2 = TreeNode2("1.2", "Child 2")
        val grandChild1 = TreeNode2("1.2.1", "Grandchild 1")
        grandChild1.children.addAll(
            listOf(
                TreeNode2("1.2.1", "Grandchild 2"),
                TreeNode2("1.2.1", "Grandchild 3")
            )
        )
        child2.children.add(grandChild1)
        root.children.addAll(listOf(child1, child2))
    }

    fun select(node: TreeNode2, selected: Boolean = !node.selected) {
        node.selected = selected


        if (!selected) {
            // don't deselect children
            return
        }

        val currentStack = ArrayDeque<TreeNode2>()

        currentStack.add(node)

        while (currentStack.isNotEmpty()) {
            val current = currentStack.removeFirst()
            current.selected = true

            currentStack.addAll(current.children)
        }
    }


}

class ItemTreeNodeGenerator(
    private val rootSource: DataSource
) : TreeNodeGenerator<TreeNode2> {


    override fun createNode(
        parentNode: TreeNode<TreeNode2>,
        currentData: TreeNode2,
        tree: AbstractTree<TreeNode2>
    ): TreeNode<TreeNode2> {
        return TreeNode(
            data = currentData,
            depth = parentNode.depth + 1,
            name = currentData.name,
            id = tree.generateId(),
            hasChild = currentData.children.isNotEmpty(),
            // It should be taken from the Item
            isChild = currentData.children.isNotEmpty(),
            expand = false,
            selected = currentData.selected
        )
    }

    override fun createRootNode(): TreeNode<TreeNode2> {
        return TreeNode(
            data = rootSource.root,
            // Set to -1 to not show the root node
            depth = -1,
            name = rootSource.root.name,
            id = Tree.ROOT_NODE_ID,
            hasChild = true,
            isChild = true
        )
    }

    override suspend fun fetchChildData(targetNode: TreeNode<TreeNode2>): Set<TreeNode2> {
        return targetNode.requireData().children.toSet()
    }


}
```
